### ISSUE TITLE
sls v3 support

### ISSUE THREAD

**Issue by niradler** [aronim/serverless-plugin-parent#8]
hi anyone knows maybe what are the changes needed to support sls v3 ?

**Comment by kevinsewell** [comment]
Hi Nir, 

It appears that this plugin is no longer compatible with sls v3 :-( I am think of writing a wrapper for sls that would make provision for a different type of plugin that generates/modifies the serverless.yml file. Is that something you would be interested in testing out?

**Comment by niradler** [comment]
sure, the changes will be permanent or will be revert after each run?

**Comment by kevinsewell** [comment]
The idea is that you would use the wrapper script, something like `slsw`, instead of `sls` to run serverless tasks. 

The `slsw` script would use the specified `serverless.yml`, which would include a number of `serverless-wrapper-plugin-*` entries, to generate the effective `serverless.yml` file but at a temporary location, maybe `<project>/.slsw/serverless.yml`. 

Then the `slsw` script will trigger `serverless --conf ./.slsw/serverless.yml <tasks>`.

**Comment by niradler** [comment]
we decided to use serverless.js  and then we can merge js object 
_In case you need more flexibility, you can also define the service configuration in JSON (serverless.json), JavaScript (serverless.js) or TypeScript (serverless.ts)._

**Comment by kevinsewell** [comment]
Ah, that sounds good :-)
